package Leisure;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;

import javax.swing.ButtonGroup;

import java.awt.Toolkit;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.JCheckBox;
import javax.swing.JButton;
import javax.swing.JComboBox;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import com.toedter.calendar.JDateChooser;
import com.toedter.components.JLocaleChooser;
import com.toedter.calendar.JDayChooser;
import com.toedter.calendar.demo.DateChooserPanel;

import java.awt.Checkbox;
import java.awt.Button;
import javax.swing.JRadioButton;
/**
 *
 * @author l00115280
 */
public class leisureCentreProject extends javax.swing.JFrame {

	/**
	 * 
	 */
	private leisure_DB lDB = new leisure_DB();
	private JDateChooser dateChooser = new JDateChooser();
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form leisureCentreProject
	 */
	public leisureCentreProject() {
		initComponents();
		this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
	}

	/**
	 * This method is called from within the constructor to initialise the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		
		
		Font tabFont = new Font("Tahoma",Font.BOLD|Font.ITALIC,18);
		
		dateChooser.setFont(new Font("Tahoma",Font.ITALIC,16));
		
		jTabbedPane6 = new javax.swing.JTabbedPane();
		
		jTabbedPane6.setFont(tabFont);
		
		jTabbedPane1 = new javax.swing.JTabbedPane();
		
		jTabbedPane1.setFont(tabFont);
		
		LeisureCentre = new javax.swing.JTabbedPane();
		
		LeisureCentre.setFont(tabFont);
		
		jPanel1 = new javax.swing.JPanel();
		jComboBox1 = new javax.swing.JComboBox<>();
		jComboBox1.setFont(new Font("Tahoma", Font.ITALIC, 18));
		jComboBox2 = new javax.swing.JComboBox<>();
		jComboBox2.setFont(new Font("Tahoma", Font.ITALIC, 18));
		jComboBox3 = new javax.swing.JComboBox<>();
		jComboBox3.setFont(new Font("Tahoma", Font.ITALIC, 18));
		jComboBox4 = new javax.swing.JComboBox<>();
		jComboBox4.setFont(new Font("Tahoma", Font.ITALIC, 18));
		jButton1 = new javax.swing.JButton();
		jButton1.setFont(new Font("Tahoma", Font.BOLD, 18));
		
		
		jTabbedPane3 = new javax.swing.JTabbedPane();
		
		jTabbedPane3.setFont(tabFont);
		
		jPanel3 = new javax.swing.JPanel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea3 = new javax.swing.JTextArea();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTextArea4 = new javax.swing.JTextArea();
		jButton3 = new javax.swing.JButton();
		
		ButtonGroup bg = new ButtonGroup();
		
		
		//System.out.print(dateChooser.getDate());
		jButton1.addActionListener(new ActionListener() {public void actionPerformed(ActionEvent confirmAE){
			
			//yyyy-mm-dd
			
			//1900
			//1
			
			try{
			String jOut = "NOT WORKING";
			
			
			if(rdbtnNewRadioButton.isSelected()){
				  jOut = (String) jComboBox1.getSelectedItem();
			}
			if(rdbtnNewRadioButton_1.isSelected()){
				  jOut = (String) jComboBox2.getSelectedItem();
			}
			if(rdbtnNewRadioButton_2.isSelected()){
				  jOut = (String) jComboBox3.getSelectedItem();
			}
			if(rdbtnNewRadioButton_3.isSelected()){
				  jOut = (String) jComboBox4.getSelectedItem();
			}
			
			int cIdent = 0;
			
			switch(jOut){
			case "Circuits": cIdent = 1;
				break;
			case "Spinning": cIdent = 2;
				break;
			case "KettleBell": cIdent = 3;
				break;
			case "Adult's PT": cIdent = 5;
				break;
			case "Swimming": cIdent = 6;
			break;
			case "Aqua Aerobics": cIdent = 7;
			break;
			case "Beginner's": cIdent = 8;
			break;
			case "Children's": cIdent = 9;
			break;
			case "Basketball": cIdent = 10;
			break;
			case "Football": cIdent = 11;
			break;
			case "Tennis": cIdent = 12;
			break;
			case "Racketball": cIdent = 13;
			break;
			case "HIIT": cIdent = 14;
			break;
			default : cIdent = -1;
			}
			
			
			int year,month,day;
			String sDay,sMonth,sFinalDate = null;
			day = dateChooser.getDate().getDate();
			month = dateChooser.getDate().getMonth() + 1;
			year = dateChooser.getDate().getYear() + 1900;
			
			if(day < 10){
				sDay = "0" + day;
			}
			else{
				sDay = Integer.toString(day);
			}
			if(month < 10){
				sMonth = "0" + month;
			}
			else{
				sMonth = Integer.toString(month);
			}
			
			sFinalDate = year + "-" + sMonth + "-" + sDay;
			
			//Tester stuff making sure outputs are as they should be
			System.out.println(lDB.isFull(cIdent, sFinalDate));
			
			System.out.print(sFinalDate+"\n");
		
			
			if(lDB.isFull(cIdent,sFinalDate)){
				
				UIManager.put("OptionPane.messageFont", new Font("TimesNewRoman",Font.BOLD,20));
				UIManager.put("OptionPane.buttonFont", new Font("SansSerif",Font.BOLD,20));
				JOptionPane.showMessageDialog(null,"Sorry! No Booking available.","Please Try Again",JOptionPane.INFORMATION_MESSAGE);
			}
			else{
				UIManager.put("OptionPane.messageFont", new Font("TimesNewRoman",Font.BOLD,20));
				UIManager.put("OptionPane.buttonFont", new Font("SansSerif",Font.BOLD,20));
				JOptionPane.showMessageDialog(null,"Sorry! No Booking available.","Please Try Again",JOptionPane.INFORMATION_MESSAGE);
			}
			}
			catch(Exception e){
				System.out.println(e.getMessage());
				UIManager.put("OptionPane.messageFont", new Font("TimesNewRoman",Font.BOLD,20));
				UIManager.put("OptionPane.buttonFont", new Font("SansSerif",Font.BOLD,20));
				JOptionPane.showMessageDialog(null,"NO DATE SELECTED!","Please Try Again",JOptionPane.WARNING_MESSAGE);
			}
			finally{
				jButton1.setEnabled(false);
				jComboBox1.setEnabled(false);
				jComboBox2.setEnabled(false);
				jComboBox3.setEnabled(false);
				jComboBox4.setEnabled(false);
				bg.clearSelection();
				dateChooser.setEnabled(false);
			}
			
		}} );
		
		
		
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Circuits", "KettleBell", "Spinning", "Adult's PT" }));
		jComboBox1.setEnabled(false);
		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Swimming", "Aqua Aerobics", "Beginner's", "Children's" }));
		jComboBox2.setEnabled(false);
		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basketball", "Football", "Tennis", "Racketball" }));
		jComboBox3.setEnabled(false);
		jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HIIT", "Item 2", "Item 3", "Item 4" }));
		jComboBox4.setEnabled(false);
		jButton1.setText("Check Availability");
		
		
		dateChooser.setEnabled(false);
		jButton1.setEnabled(false);
		
		
		rdbtnNewRadioButton = new JRadioButton("Indoor");
		rdbtnNewRadioButton.setFont(new Font("Tahoma", Font.BOLD, 18));
		rdbtnNewRadioButton.addActionListener(new ActionListener() {public void actionPerformed(ActionEvent confirmAE){
			jComboBox1.setEnabled(true);
			jComboBox2.setEnabled(false);
			jComboBox3.setEnabled(false);
			jComboBox4.setEnabled(false);
			
			dateChooser.setEnabled(true);
			jButton1.setEnabled(true);
		}});
		
		rdbtnNewRadioButton_1 = new JRadioButton("Aquatic");
		rdbtnNewRadioButton_1.setFont(new Font("Tahoma", Font.BOLD, 18));
		rdbtnNewRadioButton_1.addActionListener(new ActionListener() {public void actionPerformed(ActionEvent confirmAE){
			jComboBox2.setEnabled(true);
			jComboBox1.setEnabled(false);
			jComboBox3.setEnabled(false);
			jComboBox4.setEnabled(false);
			
			dateChooser.setEnabled(true);
			jButton1.setEnabled(true);
		}});
		
		
		rdbtnNewRadioButton_2 = new JRadioButton("Sports");
		rdbtnNewRadioButton_2.setFont(new Font("Tahoma", Font.BOLD, 18));
		rdbtnNewRadioButton_2.addActionListener(new ActionListener() {public void actionPerformed(ActionEvent confirmAE){
			jComboBox3.setEnabled(true);
			jComboBox2.setEnabled(false);
			jComboBox1.setEnabled(false);
			jComboBox4.setEnabled(false);
			
			dateChooser.setEnabled(true);
			jButton1.setEnabled(true);
		}});
		
		
		rdbtnNewRadioButton_3 = new JRadioButton("Fitness");
		rdbtnNewRadioButton_3.setFont(new Font("Tahoma", Font.BOLD, 18));
		rdbtnNewRadioButton_3.addActionListener(new ActionListener() {public void actionPerformed(ActionEvent confirmAE){
			jComboBox4.setEnabled(true);
			jComboBox2.setEnabled(false);
			jComboBox3.setEnabled(false);
			jComboBox1.setEnabled(false);
			
			dateChooser.setEnabled(true);
			jButton1.setEnabled(true);
		}});
		
		
		
		bg.add(rdbtnNewRadioButton);
		bg.add(rdbtnNewRadioButton_1);
		bg.add(rdbtnNewRadioButton_2);
		bg.add(rdbtnNewRadioButton_3);
		
		
		
		JLabel lblActivities = new JLabel("Activities:");
		lblActivities.setFont(new Font("Tahoma", Font.BOLD, 19));
		
		lblNewLabel = new JLabel("Please Select a Date");
		lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 19));
		

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(63)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(lblNewLabel)
						.addComponent(lblActivities)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(dateChooser, GroupLayout.PREFERRED_SIZE, 331, GroupLayout.PREFERRED_SIZE)
							.addGap(18)
							.addComponent(jButton1, GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(rdbtnNewRadioButton, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
								.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, 123, GroupLayout.PREFERRED_SIZE))
							.addGap(18)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, 128, GroupLayout.PREFERRED_SIZE)
								.addComponent(rdbtnNewRadioButton_1))
							.addGap(33)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(rdbtnNewRadioButton_2)
								.addComponent(jComboBox3, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(rdbtnNewRadioButton_3)
								.addComponent(jComboBox4, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE))))
					.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(54)
					.addComponent(lblActivities)
					.addGap(18)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(rdbtnNewRadioButton)
						.addComponent(rdbtnNewRadioButton_1)
						.addComponent(rdbtnNewRadioButton_3)
						.addComponent(rdbtnNewRadioButton_2))
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jComboBox3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jComboBox4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(107)
					.addComponent(lblNewLabel)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(dateChooser, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton1))
					.addContainerGap(233, Short.MAX_VALUE))
		);
		
		
		jPanel1.setLayout(jPanel1Layout);

		LeisureCentre.addTab("Booking", jPanel1);

		ButtonGroup bGroup = new ButtonGroup();
		LeisureCentre.addTab("Membership", jTabbedPane3);
		jPanel2 = new javax.swing.JPanel();
		
				jTabbedPane3.addTab("New Member", jPanel2);
				GridBagLayout gbl_jPanel2 = new GridBagLayout();
				gbl_jPanel2.columnWidths = new int[] {-11, 98, 165, 43, 0, 125};
				gbl_jPanel2.rowHeights = new int[]{27, 26, 43, 39, 26, 33, 0, 33, 33, 33, 35, 0};
				gbl_jPanel2.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
				gbl_jPanel2.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
				jPanel2.setLayout(gbl_jPanel2);
				jLabel9 = new javax.swing.JLabel();
				jLabel9.setFont(new Font("Tahoma", Font.BOLD, 18));
				
						jLabel9.setText("Member Details");
						GridBagConstraints gbc_jLabel9 = new GridBagConstraints();
						gbc_jLabel9.anchor = GridBagConstraints.NORTHWEST;
						gbc_jLabel9.insets = new Insets(0, 0, 5, 5);
						gbc_jLabel9.gridx = 1;
						gbc_jLabel9.gridy = 0;
						jPanel2.add(jLabel9, gbc_jLabel9);
								jLabel10 = new javax.swing.JLabel();
								jLabel10.setFont(new Font("Tahoma", Font.BOLD, 20));
								
										jLabel10.setText("Membership Details");
										GridBagConstraints gbc_jLabel10 = new GridBagConstraints();
										gbc_jLabel10.anchor = GridBagConstraints.SOUTHWEST;
										gbc_jLabel10.insets = new Insets(0, 0, 5, 5);
										gbc_jLabel10.gridx = 4;
										gbc_jLabel10.gridy = 0;
										jPanel2.add(jLabel10, gbc_jLabel10);
								jLabel1 = new javax.swing.JLabel();
								jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 18));
								
										jLabel1.setText("Mem Id");
										GridBagConstraints gbc_jLabel1 = new GridBagConstraints();
										gbc_jLabel1.anchor = GridBagConstraints.NORTHWEST;
										gbc_jLabel1.insets = new Insets(0, 0, 5, 5);
										gbc_jLabel1.gridx = 1;
										gbc_jLabel1.gridy = 1;
										jPanel2.add(jLabel1, gbc_jLabel1);
												jTextField1 = new javax.swing.JTextField();
												
														jTextField1.setText("jTextField1");
														GridBagConstraints gbc_jTextField1 = new GridBagConstraints();
														gbc_jTextField1.anchor = GridBagConstraints.NORTH;
														gbc_jTextField1.fill = GridBagConstraints.HORIZONTAL;
														gbc_jTextField1.insets = new Insets(0, 0, 5, 5);
														gbc_jTextField1.gridx = 2;
														gbc_jTextField1.gridy = 1;
														jPanel2.add(jTextField1, gbc_jTextField1);
																jLabel11 = new javax.swing.JLabel();
																jLabel11.setFont(new Font("Tahoma", Font.PLAIN, 18));
																
																		jLabel11.setText("Membership type:");
																		GridBagConstraints gbc_jLabel11 = new GridBagConstraints();
																		gbc_jLabel11.anchor = GridBagConstraints.NORTHWEST;
																		gbc_jLabel11.insets = new Insets(0, 0, 5, 5);
																		gbc_jLabel11.gridx = 4;
																		gbc_jLabel11.gridy = 1;
																		jPanel2.add(jLabel11, gbc_jLabel11);
																jLabel2 = new javax.swing.JLabel();
																jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 18));
																
																		jLabel2.setText("Title");
																		GridBagConstraints gbc_jLabel2 = new GridBagConstraints();
																		gbc_jLabel2.anchor = GridBagConstraints.WEST;
																		gbc_jLabel2.insets = new Insets(0, 0, 5, 5);
																		gbc_jLabel2.gridx = 1;
																		gbc_jLabel2.gridy = 2;
																		jPanel2.add(jLabel2, gbc_jLabel2);
																				jTextField2 = new javax.swing.JTextField();
																				
																						jTextField2.setText("jTextField2");
																						GridBagConstraints gbc_jTextField2 = new GridBagConstraints();
																						gbc_jTextField2.fill = GridBagConstraints.HORIZONTAL;
																						gbc_jTextField2.insets = new Insets(0, 0, 5, 5);
																						gbc_jTextField2.gridx = 2;
																						gbc_jTextField2.gridy = 2;
																						jPanel2.add(jTextField2, gbc_jTextField2);
																						jComboBox7 = new javax.swing.JComboBox<>();
																						jComboBox7.setFont(new Font("Tahoma", Font.PLAIN, 18));
																						
																								jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
																								jComboBox7.addActionListener(new java.awt.event.ActionListener() {
																									public void actionPerformed(java.awt.event.ActionEvent evt) {
																										jComboBox7ActionPerformed(evt);
																									}
																								});
																								GridBagConstraints gbc_jComboBox7 = new GridBagConstraints();
																								gbc_jComboBox7.anchor = GridBagConstraints.WEST;
																								gbc_jComboBox7.insets = new Insets(0, 0, 5, 5);
																								gbc_jComboBox7.gridx = 4;
																								gbc_jComboBox7.gridy = 2;
																								jPanel2.add(jComboBox7, gbc_jComboBox7);
																						jLabel3 = new javax.swing.JLabel();
																						jLabel3.setFont(new Font("Tahoma", Font.PLAIN, 18));
																						
																								jLabel3.setText("First Name");
																								GridBagConstraints gbc_jLabel3 = new GridBagConstraints();
																								gbc_jLabel3.fill = GridBagConstraints.HORIZONTAL;
																								gbc_jLabel3.insets = new Insets(0, 0, 5, 5);
																								gbc_jLabel3.gridx = 1;
																								gbc_jLabel3.gridy = 3;
																								jPanel2.add(jLabel3, gbc_jLabel3);
																										jTextField3 = new javax.swing.JTextField();
																										
																												jTextField3.setText("jTextField3");
																												GridBagConstraints gbc_jTextField3 = new GridBagConstraints();
																												gbc_jTextField3.fill = GridBagConstraints.HORIZONTAL;
																												gbc_jTextField3.insets = new Insets(0, 0, 5, 5);
																												gbc_jTextField3.gridx = 2;
																												gbc_jTextField3.gridy = 3;
																												jPanel2.add(jTextField3, gbc_jTextField3);
																												
																														JLabel label_10 = new JLabel();
																														label_10.setText("Category:");
																														label_10.setFont(new Font("Tahoma", Font.PLAIN, 18));
																														GridBagConstraints gbc_label_10 = new GridBagConstraints();
																														gbc_label_10.fill = GridBagConstraints.HORIZONTAL;
																														gbc_label_10.insets = new Insets(0, 0, 5, 5);
																														gbc_label_10.gridx = 4;
																														gbc_label_10.gridy = 3;
																														jPanel2.add(label_10, gbc_label_10);
																												jLabel4 = new javax.swing.JLabel();
																												jLabel4.setFont(new Font("Tahoma", Font.PLAIN, 18));
																												
																														jLabel4.setText("Surname");
																														GridBagConstraints gbc_jLabel4 = new GridBagConstraints();
																														gbc_jLabel4.anchor = GridBagConstraints.WEST;
																														gbc_jLabel4.insets = new Insets(0, 0, 5, 5);
																														gbc_jLabel4.gridx = 1;
																														gbc_jLabel4.gridy = 4;
																														jPanel2.add(jLabel4, gbc_jLabel4);
																														jTextField4 = new javax.swing.JTextField();
																														
																																jTextField4.setText("jTextField4");
																																GridBagConstraints gbc_jTextField4 = new GridBagConstraints();
																																gbc_jTextField4.fill = GridBagConstraints.HORIZONTAL;
																																gbc_jTextField4.insets = new Insets(0, 0, 5, 5);
																																gbc_jTextField4.gridx = 2;
																																gbc_jTextField4.gridy = 4;
																																jPanel2.add(jTextField4, gbc_jTextField4);
																																		jCheckBox1 = new javax.swing.JCheckBox();
																																		jCheckBox1.setFont(new Font("Tahoma", Font.PLAIN, 20));
																																		
																																				jCheckBox1.setText("Student");
																																				bGroup.add(jCheckBox1);
																																				GridBagConstraints gbc_jCheckBox1 = new GridBagConstraints();
																																				gbc_jCheckBox1.anchor = GridBagConstraints.WEST;
																																				gbc_jCheckBox1.insets = new Insets(0, 0, 5, 5);
																																				gbc_jCheckBox1.gridx = 4;
																																				gbc_jCheckBox1.gridy = 4;
																																				jPanel2.add(jCheckBox1, gbc_jCheckBox1);
																																		jLabel5 = new javax.swing.JLabel();
																																		jLabel5.setFont(new Font("Tahoma", Font.PLAIN, 18));
																																		
																																				jLabel5.setText("Address");
																																				GridBagConstraints gbc_jLabel5 = new GridBagConstraints();
																																				gbc_jLabel5.anchor = GridBagConstraints.WEST;
																																				gbc_jLabel5.insets = new Insets(0, 0, 5, 5);
																																				gbc_jLabel5.gridx = 1;
																																				gbc_jLabel5.gridy = 5;
																																				jPanel2.add(jLabel5, gbc_jLabel5);
																																						jTextField5 = new javax.swing.JTextField();
																																						
																																								jTextField5.setText("jTextField5");
																																								GridBagConstraints gbc_jTextField5 = new GridBagConstraints();
																																								gbc_jTextField5.fill = GridBagConstraints.HORIZONTAL;
																																								gbc_jTextField5.insets = new Insets(0, 0, 5, 5);
																																								gbc_jTextField5.gridx = 2;
																																								gbc_jTextField5.gridy = 5;
																																								jPanel2.add(jTextField5, gbc_jTextField5);
																																								jCheckBox2 = new javax.swing.JCheckBox();
																																								jCheckBox2.setFont(new Font("Tahoma", Font.PLAIN, 20));
																																								
																																										jCheckBox2.setText("O.A.P(66+)");
																																										jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
																																											public void actionPerformed(java.awt.event.ActionEvent evt) {
																																												jCheckBox2ActionPerformed(evt);
																																											}
																																										});
																																										bGroup.add(jCheckBox2);
																																										GridBagConstraints gbc_jCheckBox2 = new GridBagConstraints();
																																										gbc_jCheckBox2.anchor = GridBagConstraints.WEST;
																																										gbc_jCheckBox2.insets = new Insets(0, 0, 5, 5);
																																										gbc_jCheckBox2.gridx = 4;
																																										gbc_jCheckBox2.gridy = 5;
																																										jPanel2.add(jCheckBox2, gbc_jCheckBox2);
																																								jLabel6 = new javax.swing.JLabel();
																																								jLabel6.setFont(new Font("Tahoma", Font.PLAIN, 18));
																																								
																																										jLabel6.setText("Postcode");
																																										GridBagConstraints gbc_jLabel6 = new GridBagConstraints();
																																										gbc_jLabel6.anchor = GridBagConstraints.WEST;
																																										gbc_jLabel6.insets = new Insets(0, 0, 5, 5);
																																										gbc_jLabel6.gridx = 1;
																																										gbc_jLabel6.gridy = 6;
																																										jPanel2.add(jLabel6, gbc_jLabel6);
																																												jTextField6 = new javax.swing.JTextField();
																																												
																																														jTextField6.setText("jTextField6");
																																														GridBagConstraints gbc_jTextField6 = new GridBagConstraints();
																																														gbc_jTextField6.fill = GridBagConstraints.HORIZONTAL;
																																														gbc_jTextField6.insets = new Insets(0, 0, 5, 5);
																																														gbc_jTextField6.gridx = 2;
																																														gbc_jTextField6.gridy = 6;
																																														jPanel2.add(jTextField6, gbc_jTextField6);
																																														jCheckBox3 = new javax.swing.JCheckBox();
																																														jCheckBox3.setFont(new Font("Tahoma", Font.PLAIN, 20));
																																														
																																																jCheckBox3.setText("Family");
																																																jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
																																																	public void actionPerformed(java.awt.event.ActionEvent evt) {
																																																		jCheckBox3ActionPerformed(evt);
																																																	}
																																																});
																																																bGroup.add(jCheckBox3);
																																																GridBagConstraints gbc_jCheckBox3 = new GridBagConstraints();
																																																gbc_jCheckBox3.anchor = GridBagConstraints.WEST;
																																																gbc_jCheckBox3.insets = new Insets(0, 0, 5, 5);
																																																gbc_jCheckBox3.gridx = 4;
																																																gbc_jCheckBox3.gridy = 6;
																																																jPanel2.add(jCheckBox3, gbc_jCheckBox3);
																																														jLabel7 = new javax.swing.JLabel();
																																														jLabel7.setFont(new Font("Tahoma", Font.PLAIN, 18));
																																														
																																																jLabel7.setText("Contact #");
																																																GridBagConstraints gbc_jLabel7 = new GridBagConstraints();
																																																gbc_jLabel7.anchor = GridBagConstraints.WEST;
																																																gbc_jLabel7.insets = new Insets(0, 0, 5, 5);
																																																gbc_jLabel7.gridx = 1;
																																																gbc_jLabel7.gridy = 7;
																																																jPanel2.add(jLabel7, gbc_jLabel7);
																																																jTextField7 = new javax.swing.JTextField();
																																																
																																																		jTextField7.setText("jTextField7");
																																																		GridBagConstraints gbc_jTextField7 = new GridBagConstraints();
																																																		gbc_jTextField7.fill = GridBagConstraints.HORIZONTAL;
																																																		gbc_jTextField7.insets = new Insets(0, 0, 5, 5);
																																																		gbc_jTextField7.gridx = 2;
																																																		gbc_jTextField7.gridy = 7;
																																																		jPanel2.add(jTextField7, gbc_jTextField7);
																																																				jCheckBox4 = new javax.swing.JCheckBox();
																																																				jCheckBox4.setFont(new Font("Tahoma", Font.PLAIN, 20));
																																																				
																																																						jCheckBox4.setText("Child(under 16)");
																																																						bGroup.add(jCheckBox4);
																																																						GridBagConstraints gbc_jCheckBox4 = new GridBagConstraints();
																																																						gbc_jCheckBox4.anchor = GridBagConstraints.WEST;
																																																						gbc_jCheckBox4.insets = new Insets(0, 0, 5, 5);
																																																						gbc_jCheckBox4.gridx = 4;
																																																						gbc_jCheckBox4.gridy = 7;
																																																						jPanel2.add(jCheckBox4, gbc_jCheckBox4);
																																																				jLabel8 = new javax.swing.JLabel();
																																																				jLabel8.setFont(new Font("Tahoma", Font.PLAIN, 18));
																																																				
																																																						jLabel8.setText("D.O.B");
																																																						GridBagConstraints gbc_jLabel8 = new GridBagConstraints();
																																																						gbc_jLabel8.anchor = GridBagConstraints.WEST;
																																																						gbc_jLabel8.insets = new Insets(0, 0, 5, 5);
																																																						gbc_jLabel8.gridx = 1;
																																																						gbc_jLabel8.gridy = 8;
																																																						jPanel2.add(jLabel8, gbc_jLabel8);
																																																								jTextField8 = new javax.swing.JTextField();
																																																								
																																																										jTextField8.setText("jTextField8");
																																																										GridBagConstraints gbc_jTextField8 = new GridBagConstraints();
																																																										gbc_jTextField8.fill = GridBagConstraints.HORIZONTAL;
																																																										gbc_jTextField8.insets = new Insets(0, 0, 5, 5);
																																																										gbc_jTextField8.gridx = 2;
																																																										gbc_jTextField8.gridy = 8;
																																																										jPanel2.add(jTextField8, gbc_jTextField8);
																																																										jButton2 = new javax.swing.JButton();
																																																										
																																																												jButton2.setText("Create Member");
																																																												jButton2.addActionListener(new java.awt.event.ActionListener() {
																																																													public void actionPerformed(java.awt.event.ActionEvent evt) {
																																																														jButton2ActionPerformed(evt);
																																																													}
																																																												});
																																																												GridBagConstraints gbc_jButton2 = new GridBagConstraints();
																																																												gbc_jButton2.fill = GridBagConstraints.HORIZONTAL;
																																																												gbc_jButton2.insets = new Insets(0, 0, 5, 5);
																																																												gbc_jButton2.gridx = 4;
																																																												gbc_jButton2.gridy = 8;
																																																												jPanel2.add(jButton2, gbc_jButton2);

		panel = new JPanel();
		jTabbedPane3.addTab("Edit Memeber", null, panel, null);
		GridBagLayout gbl_panel = new GridBagLayout();
		gbl_panel.columnWidths = new int[] {30, 30, 160, 30, 167, 81, 30, 82};
		gbl_panel.rowHeights = new int[]{27, 0, 26, 29, 29, 26, 26, 26, 26, 39, 0};
		gbl_panel.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
		gbl_panel.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		panel.setLayout(gbl_panel);
										
												label = new JLabel();
												label.setText("Member To Update");
												label.setFont(new Font("Tahoma", Font.BOLD, 22));
												GridBagConstraints gbc_label = new GridBagConstraints();
												gbc_label.anchor = GridBagConstraints.NORTHWEST;
												gbc_label.insets = new Insets(0, 0, 5, 5);
												gbc_label.gridwidth = 3;
												gbc_label.gridx = 1;
												gbc_label.gridy = 0;
												panel.add(label, gbc_label);
								
										label_9 = new JLabel();
										label_9.setText("Member ID");
										label_9.setFont(new Font("Tahoma", Font.BOLD, 22));
										GridBagConstraints gbc_label_9 = new GridBagConstraints();
										gbc_label_9.anchor = GridBagConstraints.NORTHWEST;
										gbc_label_9.insets = new Insets(0, 0, 5, 5);
										gbc_label_9.gridwidth = 4;
										gbc_label_9.gridx = 4;
										gbc_label_9.gridy = 0;
										panel.add(label_9, gbc_label_9);
														
																label_6 = new JLabel();
																label_6.setFont(new Font("Tahoma", Font.PLAIN, 18));
																label_6.setText("Title");
																GridBagConstraints gbc_label_6 = new GridBagConstraints();
																gbc_label_6.anchor = GridBagConstraints.NORTH;
																gbc_label_6.fill = GridBagConstraints.HORIZONTAL;
																gbc_label_6.insets = new Insets(0, 0, 5, 5);
																gbc_label_6.gridx = 1;
																gbc_label_6.gridy = 2;
																panel.add(label_6, gbc_label_6);
												
														textField_1 = new JTextField();
														textField_1.setText("jTextField2");
														GridBagConstraints gbc_textField_1 = new GridBagConstraints();
														gbc_textField_1.anchor = GridBagConstraints.NORTH;
														gbc_textField_1.fill = GridBagConstraints.HORIZONTAL;
														gbc_textField_1.insets = new Insets(0, 0, 5, 5);
														gbc_textField_1.gridx = 2;
														gbc_textField_1.gridy = 2;
														panel.add(textField_1, gbc_textField_1);
										
												label_3 = new JLabel();
												label_3.setFont(new Font("Tahoma", Font.PLAIN, 18));
												label_3.setText("Mem Id");
												GridBagConstraints gbc_label_3 = new GridBagConstraints();
												gbc_label_3.anchor = GridBagConstraints.NORTHWEST;
												gbc_label_3.insets = new Insets(0, 0, 5, 5);
												gbc_label_3.gridx = 4;
												gbc_label_3.gridy = 2;
												panel.add(label_3, gbc_label_3);
								
										textField = new JTextField();
										textField.setText("jTextField1");
										GridBagConstraints gbc_textField = new GridBagConstraints();
										gbc_textField.fill = GridBagConstraints.HORIZONTAL;
										gbc_textField.anchor = GridBagConstraints.NORTH;
										gbc_textField.insets = new Insets(0, 0, 5, 5);
										gbc_textField.gridwidth = 3;
										gbc_textField.gridx = 5;
										gbc_textField.gridy = 2;
										panel.add(textField, gbc_textField);
				
						JButton button_1 = new JButton();
						button_1.addActionListener(new ActionListener() {
							public void actionPerformed(ActionEvent e) {
							}
						});
								
										label_7 = new JLabel();
										label_7.setFont(new Font("Tahoma", Font.PLAIN, 18));
										label_7.setText("First Name");
										GridBagConstraints gbc_label_7 = new GridBagConstraints();
										gbc_label_7.anchor = GridBagConstraints.WEST;
										gbc_label_7.insets = new Insets(0, 0, 5, 5);
										gbc_label_7.gridx = 1;
										gbc_label_7.gridy = 3;
										panel.add(label_7, gbc_label_7);
						
								textField_2 = new JTextField();
								textField_2.setText("jTextField3");
								GridBagConstraints gbc_textField_2 = new GridBagConstraints();
								gbc_textField_2.anchor = GridBagConstraints.NORTH;
								gbc_textField_2.fill = GridBagConstraints.HORIZONTAL;
								gbc_textField_2.insets = new Insets(0, 0, 5, 5);
								gbc_textField_2.gridx = 2;
								gbc_textField_2.gridy = 3;
								panel.add(textField_2, gbc_textField_2);
						button_1.setText("Confirm Member");
						GridBagConstraints gbc_button_1 = new GridBagConstraints();
						gbc_button_1.anchor = GridBagConstraints.NORTHWEST;
						gbc_button_1.insets = new Insets(0, 0, 5, 5);
						gbc_button_1.gridx = 4;
						gbc_button_1.gridy = 3;
						panel.add(button_1, gbc_button_1);
														
																label_8 = new JLabel();
																label_8.setFont(new Font("Tahoma", Font.PLAIN, 18));
																label_8.setText("Surname");
																GridBagConstraints gbc_label_8 = new GridBagConstraints();
																gbc_label_8.anchor = GridBagConstraints.NORTHWEST;
																gbc_label_8.insets = new Insets(0, 0, 5, 5);
																gbc_label_8.gridx = 1;
																gbc_label_8.gridy = 4;
																panel.add(label_8, gbc_label_8);
														
																textField_3 = new JTextField();
																textField_3.setText("jTextField4");
																GridBagConstraints gbc_textField_3 = new GridBagConstraints();
																gbc_textField_3.anchor = GridBagConstraints.SOUTH;
																gbc_textField_3.fill = GridBagConstraints.HORIZONTAL;
																gbc_textField_3.insets = new Insets(0, 0, 5, 5);
																gbc_textField_3.gridx = 2;
																gbc_textField_3.gridy = 4;
																panel.add(textField_3, gbc_textField_3);
												
														label_4 = new JLabel();
														label_4.setFont(new Font("Tahoma", Font.PLAIN, 18));
														label_4.setText("Address");
														GridBagConstraints gbc_label_4 = new GridBagConstraints();
														gbc_label_4.anchor = GridBagConstraints.NORTHWEST;
														gbc_label_4.insets = new Insets(0, 0, 5, 5);
														gbc_label_4.gridx = 1;
														gbc_label_4.gridy = 5;
														panel.add(label_4, gbc_label_4);
												
														textField_4 = new JTextField();
														textField_4.setText("jTextField5");
														GridBagConstraints gbc_textField_4 = new GridBagConstraints();
														gbc_textField_4.anchor = GridBagConstraints.NORTH;
														gbc_textField_4.fill = GridBagConstraints.HORIZONTAL;
														gbc_textField_4.insets = new Insets(0, 0, 5, 5);
														gbc_textField_4.gridx = 2;
														gbc_textField_4.gridy = 5;
														panel.add(textField_4, gbc_textField_4);
										
												label_5 = new JLabel();
												label_5.setFont(new Font("Tahoma", Font.PLAIN, 18));
												label_5.setText("Postcode");
												GridBagConstraints gbc_label_5 = new GridBagConstraints();
												gbc_label_5.anchor = GridBagConstraints.NORTHWEST;
												gbc_label_5.insets = new Insets(0, 0, 5, 5);
												gbc_label_5.gridx = 1;
												gbc_label_5.gridy = 6;
												panel.add(label_5, gbc_label_5);
								
										textField_5 = new JTextField();
										textField_5.setText("jTextField6");
										GridBagConstraints gbc_textField_5 = new GridBagConstraints();
										gbc_textField_5.anchor = GridBagConstraints.NORTH;
										gbc_textField_5.fill = GridBagConstraints.HORIZONTAL;
										gbc_textField_5.insets = new Insets(0, 0, 5, 5);
										gbc_textField_5.gridx = 2;
										gbc_textField_5.gridy = 6;
										panel.add(textField_5, gbc_textField_5);
						
								label_1 = new JLabel();
								label_1.setFont(new Font("Tahoma", Font.PLAIN, 18));
								label_1.setText("Contact Number");
								GridBagConstraints gbc_label_1 = new GridBagConstraints();
								gbc_label_1.anchor = GridBagConstraints.NORTHWEST;
								gbc_label_1.insets = new Insets(0, 0, 5, 5);
								gbc_label_1.gridx = 1;
								gbc_label_1.gridy = 7;
								panel.add(label_1, gbc_label_1);
								
										textField_6 = new JTextField();
										textField_6.setText("jTextField7");
										GridBagConstraints gbc_textField_6 = new GridBagConstraints();
										gbc_textField_6.anchor = GridBagConstraints.NORTH;
										gbc_textField_6.fill = GridBagConstraints.HORIZONTAL;
										gbc_textField_6.insets = new Insets(0, 0, 5, 5);
										gbc_textField_6.gridx = 2;
										gbc_textField_6.gridy = 7;
										panel.add(textField_6, gbc_textField_6);
						
								label_2 = new JLabel();
								label_2.setFont(new Font("Tahoma", Font.PLAIN, 18));
								label_2.setText("D.O.B");
								GridBagConstraints gbc_label_2 = new GridBagConstraints();
								gbc_label_2.anchor = GridBagConstraints.NORTHWEST;
								gbc_label_2.insets = new Insets(0, 0, 5, 5);
								gbc_label_2.gridx = 1;
								gbc_label_2.gridy = 8;
								panel.add(label_2, gbc_label_2);
						
								button = new JButton();
								button.addActionListener(new ActionListener() {
									public void actionPerformed(ActionEvent e) {
									}
								});
								
										textField_7 = new JTextField();
										textField_7.setText("jTextField8");
										GridBagConstraints gbc_textField_7 = new GridBagConstraints();
										gbc_textField_7.anchor = GridBagConstraints.NORTH;
										gbc_textField_7.fill = GridBagConstraints.HORIZONTAL;
										gbc_textField_7.insets = new Insets(0, 0, 5, 5);
										gbc_textField_7.gridx = 2;
										gbc_textField_7.gridy = 8;
										panel.add(textField_7, gbc_textField_7);
								button.setText("Update Member");
								GridBagConstraints gbc_button = new GridBagConstraints();
								gbc_button.anchor = GridBagConstraints.WEST;
								gbc_button.fill = GridBagConstraints.VERTICAL;
								gbc_button.insets = new Insets(0, 0, 0, 5);
								gbc_button.gridx = 1;
								gbc_button.gridy = 9;
								panel.add(button, gbc_button);

		jTextArea3.setColumns(20);
		jTextArea3.setRows(5);
		jScrollPane3.setViewportView(jTextArea3);

		jTextArea4.setColumns(20);
		jTextArea4.setRows(5);
		jScrollPane4.setViewportView(jTextArea4);

		jButton3.setText("Enter");

		jButton3.addActionListener((new ActionListener() {public void actionPerformed(ActionEvent confirmAE){


			jTextArea3.setText(lDB.queryAllAreas());


		}
		}));


		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addGap(21, 21, 21)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup()
										.addComponent(jScrollPane4)
										.addContainerGap())
								.addGroup(jPanel3Layout.createSequentialGroup()
										.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
										.addComponent(jButton3)
										.addGap(87, 87, 87))))
				);
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addContainerGap(65, Short.MAX_VALUE)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
						.addGap(38, 38, 38)
						.addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(109, 109, 109))
				);



		LeisureCentre.addTab("Timetable", jPanel3);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(LeisureCentre)
						.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(LeisureCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 19, Short.MAX_VALUE))
				);
		jTabbedPane5 = new javax.swing.JTabbedPane();
		LeisureCentre.addTab("Admin", jTabbedPane5);

		LeisureCentre.getAccessibleContext().setAccessibleName("Booking");

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jButton2ActionPerformed

	private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jCheckBox3ActionPerformed

	private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jCheckBox2ActionPerformed

	private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jComboBox7ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				leisureCentreProject p = new leisureCentreProject();
				p.setVisible(true);
				p.pack();
				//p.setResizable(false);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTabbedPane LeisureCentre;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JCheckBox jCheckBox2;
	private javax.swing.JCheckBox jCheckBox3;
	private javax.swing.JCheckBox jCheckBox4;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JComboBox<String> jComboBox2;
	private javax.swing.JComboBox<String> jComboBox3;
	private javax.swing.JComboBox<String> jComboBox4;
	private javax.swing.JComboBox<String> jComboBox7;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTabbedPane jTabbedPane3;
	private javax.swing.JTabbedPane jTabbedPane5;
	private javax.swing.JTabbedPane jTabbedPane6;
	private javax.swing.JTextArea jTextArea3;
	private javax.swing.JTextArea jTextArea4;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	private JPanel panel;
	private JLabel label;
	private JLabel label_1;
	private JLabel label_2;
	private JLabel label_3;
	private JLabel label_4;
	private JLabel label_5;
	private JLabel label_6;
	private JLabel label_7;
	private JLabel label_8;
	private JTextField textField;
	private JTextField textField_1;
	private JTextField textField_2;
	private JTextField textField_3;
	private JTextField textField_4;
	private JTextField textField_5;
	private JTextField textField_6;
	private JTextField textField_7;
	private JLabel label_9;
	private JButton button;
	private JRadioButton rdbtnNewRadioButton;
	private JRadioButton rdbtnNewRadioButton_1;
	private JRadioButton rdbtnNewRadioButton_2;
	private JRadioButton rdbtnNewRadioButton_3;
	private JLabel lblNewLabel;
}
