package Leisure;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.sql.SQLException;
import java.util.Date;

import javax.swing.ButtonGroup;

import java.awt.Toolkit;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.JCheckBox;
import javax.swing.JButton;
import javax.swing.JComboBox;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import com.toedter.calendar.JDateChooser;
import com.toedter.components.JLocaleChooser;
import com.toedter.calendar.JDayChooser;
import com.toedter.calendar.demo.DateChooserPanel;

import java.awt.Checkbox;
import java.awt.Button;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
/**
 *
 * @author l00115280
 */
public class leisureCentreProject extends javax.swing.JFrame {

	/**
	 * 
	 */
	private leisure_DB lDB = new leisure_DB();
	private JDateChooser dateChooser = new JDateChooser();
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form leisureCentreProject
	 * @throws SQLException 
	 */
	public leisureCentreProject() throws SQLException {
		initComponents();
		this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
	}

	/**
	 * This method is called from within the constructor to initialise the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * @throws SQLException 
	 */
	//@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() throws SQLException {

		setTitle("GOBO LEISURE");

		Font tabFont = new Font("Tahoma",Font.BOLD|Font.ITALIC,18);

		table_1 = lDB.makeScheduleTable(lDB.today());		
		table_2 = lDB.makeScheduleTable(lDB.today());

		dateChooser.setFont(new Font("Tahoma",Font.ITALIC,16));

		jTabbedPane6 = new javax.swing.JTabbedPane();

		jTabbedPane6.setFont(tabFont);

		jTabbedPane1 = new javax.swing.JTabbedPane();

		jTabbedPane1.setFont(tabFont);

		LeisureCentre = new javax.swing.JTabbedPane();

		LeisureCentre.setFont(tabFont);

		jPanel1 = new javax.swing.JPanel();
		jComboBox1 = new javax.swing.JComboBox<>();
		jComboBox1.setFont(new Font("Tahoma", Font.ITALIC, 18));
		jButton1 = new javax.swing.JButton();
		jButton1.setFont(new Font("Tahoma", Font.BOLD, 18));


		jTabbedPane3 = new javax.swing.JTabbedPane();

		jTabbedPane3.setFont(tabFont);

		ButtonGroup bg = new ButtonGroup();


		jButton1.addActionListener(new ActionListener() {public void actionPerformed(ActionEvent confirmAE){

			//yyyy-mm-dd

			//1900
			//1

			try{
				String jOut = "NOT WORKING";


				/*if(rdbtnNewRadioButton.isSelected()){
					jOut = (String) jComboBox1.getSelectedItem();
				}
				if(rdbtnNewRadioButton_1.isSelected()){
					jOut = (String) jComboBox2.getSelectedItem();
				}
				if(rdbtnNewRadioButton_2.isSelected()){
					jOut = (String) jComboBox3.getSelectedItem();
				}
				if(rdbtnNewRadioButton_3.isSelected()){
					jOut = (String) jComboBox4.getSelectedItem();
				}*/

				int cIdent = 0;

				switch(jOut){
				case "Circuits": cIdent = 1;
				break;
				case "Spinning": cIdent = 2;
				break;
				case "KettleBell": cIdent = 3;
				break;
				case "Adult's PT": cIdent = 5;
				break;
				case "Swimming": cIdent = 6;
				break;
				case "Aqua Aerobics": cIdent = 7;
				break;
				case "Beginner's": cIdent = 8;
				break;
				case "Children's": cIdent = 9;
				break;
				case "Basketball": cIdent = 10;
				break;
				case "Football": cIdent = 11;
				break;
				case "Tennis": cIdent = 12;
				break;
				case "Racketball": cIdent = 13;
				break;
				case "HIIT": cIdent = 14;
				break;
				default : cIdent = -1;
				}


				int year,month,day;
				String sDay,sMonth,sFinalDate = null;
				day = dateChooser.getDate().getDate();
				month = dateChooser.getDate().getMonth() + 1;
				year = dateChooser.getDate().getYear() + 1900;



				if(day < 10){
					sDay = "0" + day;
				}
				else{
					sDay = Integer.toString(day);
				}
				if(month < 10){
					sMonth = "0" + month;
				}
				else{
					sMonth = Integer.toString(month);
				}

				sFinalDate = year + "-" + sMonth + "-" + sDay;

				//Tester stuff making sure outputs are as they should be
				System.out.println(lDB.isFull(cIdent, sFinalDate));

				System.out.print(sFinalDate+"\n");


				if(lDB.isFull(cIdent,sFinalDate)){

					UIManager.put("OptionPane.messageFont", new Font("TimesNewRoman",Font.BOLD,20));
					UIManager.put("OptionPane.buttonFont", new Font("SansSerif",Font.BOLD,20));
					JOptionPane.showMessageDialog(null,"Sorry! No Booking available.","Please Try Again",JOptionPane.INFORMATION_MESSAGE);
				}
				else{
					UIManager.put("OptionPane.messageFont", new Font("TimesNewRoman",Font.BOLD,20));
					UIManager.put("OptionPane.buttonFont", new Font("SansSerif",Font.BOLD,20));
					JOptionPane.showMessageDialog(null,"Would you like to confirm booking","Continue to Booking",JOptionPane.INFORMATION_MESSAGE);
				}
			}
			catch(Exception e){
				System.out.println(e.getMessage());
				UIManager.put("OptionPane.messageFont", new Font("TimesNewRoman",Font.BOLD,20));
				UIManager.put("OptionPane.buttonFont", new Font("SansSerif",Font.BOLD,20));
				JOptionPane.showMessageDialog(null,"NO DATE SELECTED!","Please Try Again",JOptionPane.WARNING_MESSAGE);
			}
			finally{
				/*jButton1.setEnabled(false);
				jComboBox1.setEnabled(false);
				jComboBox2.setEnabled(false);
				jComboBox3.setEnabled(false);
				jComboBox4.setEnabled(false);
				bg.clearSelection();
				dateChooser.setEnabled(false);*/
			}

		}} );



		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(lDB.getClasses()));
		jComboBox1.setEnabled(true);
		jButton1.setText("Check Availability");


		dateChooser.setEnabled(true);
		jButton1.setEnabled(true);



		JLabel lblActivities = new JLabel("Classes:");
		lblActivities.setFont(new Font("Tahoma", Font.BOLD, 19));

		lblNewLabel = new JLabel("Please Select a Date");
		lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 19));



		JScrollPane scrollPane = new JScrollPane();


		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addGap(35)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(scrollPane, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
												.addComponent(jComboBox1, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(lblActivities, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addPreferredGap(ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
												.addComponent(lblNewLabel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(dateChooser, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 331, GroupLayout.PREFERRED_SIZE)
												.addComponent(jButton1, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 250, GroupLayout.PREFERRED_SIZE))))
						.addGap(56))
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(63)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(lblActivities)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addComponent(lblNewLabel)
												.addGap(14)
												.addComponent(dateChooser, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addComponent(jButton1)))
						.addGap(62)
						.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 197, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(127, Short.MAX_VALUE))
				);



		jPanel3 = new javax.swing.JPanel();

		JScrollPane scrollPane_1 = new JScrollPane();


		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3Layout.setHorizontalGroup(
				jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addGap(78)
						.addComponent(scrollPane_1, GroupLayout.PREFERRED_SIZE, 561, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(96, Short.MAX_VALUE))
				);
		jPanel3Layout.setVerticalGroup(
				jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addGap(61)
						.addComponent(scrollPane_1, GroupLayout.PREFERRED_SIZE, 235, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(265, Short.MAX_VALUE))
				);


		scrollPane_1.setViewportView(table_2);
		jPanel3.setLayout(jPanel3Layout);



		LeisureCentre.addTab("Timetable", jPanel3);




		scrollPane.setViewportView(table_1);
		//hjsdfhsdfjhfshdfjkfdfskj

		jPanel1.setLayout(jPanel1Layout);

		LeisureCentre.addTab("Booking", jPanel1);

		ButtonGroup bGroup = new ButtonGroup();

		JPanel panel_2 = new JPanel();
		LeisureCentre.addTab("Admin Login", null, panel_2, null);
		GroupLayout gl_panel_2 = new GroupLayout(panel_2);
		gl_panel_2.setHorizontalGroup(
				gl_panel_2.createParallelGroup(Alignment.LEADING)
				.addGap(0, 735, Short.MAX_VALUE)
				);
		gl_panel_2.setVerticalGroup(
				gl_panel_2.createParallelGroup(Alignment.LEADING)
				.addGap(0, 561, Short.MAX_VALUE)
				);
		panel_2.setLayout(gl_panel_2);
		LeisureCentre.addTab("Membership", jTabbedPane3);
		jPanel2 = new javax.swing.JPanel();

		jTabbedPane3.addTab("New Member", jPanel2);
		GridBagLayout gbl_jPanel2 = new GridBagLayout();
		gbl_jPanel2.columnWidths = new int[] {-11, 98, 165, 43, 0, 125};
		gbl_jPanel2.rowHeights = new int[]{27, 26, 43, 39, 26, 33, 0, 33, 33, 33, 35, 0};
		gbl_jPanel2.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
		gbl_jPanel2.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		jPanel2.setLayout(gbl_jPanel2);
		jLabel9 = new javax.swing.JLabel();
		jLabel9.setFont(new Font("Tahoma", Font.BOLD, 20));

		jLabel9.setText("Member Details");
		GridBagConstraints gbc_jLabel9 = new GridBagConstraints();
		gbc_jLabel9.anchor = GridBagConstraints.NORTHWEST;
		gbc_jLabel9.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel9.gridx = 1;
		gbc_jLabel9.gridy = 1;
		jPanel2.add(jLabel9, gbc_jLabel9);
		jLabel10 = new javax.swing.JLabel();
		jLabel10.setFont(new Font("Tahoma", Font.BOLD, 20));

		jLabel10.setText("Membership Details");
		GridBagConstraints gbc_jLabel10 = new GridBagConstraints();
		gbc_jLabel10.anchor = GridBagConstraints.SOUTHWEST;
		gbc_jLabel10.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel10.gridx = 4;
		gbc_jLabel10.gridy = 1;
		jPanel2.add(jLabel10, gbc_jLabel10);
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 18));

		jLabel2.setText("Title");
		GridBagConstraints gbc_jLabel2 = new GridBagConstraints();
		gbc_jLabel2.anchor = GridBagConstraints.WEST;
		gbc_jLabel2.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel2.gridx = 1;
		gbc_jLabel2.gridy = 2;
		jPanel2.add(jLabel2, gbc_jLabel2);
		addMemTitle = new javax.swing.JTextField();
		GridBagConstraints gbc_addMemTitle = new GridBagConstraints();
		gbc_addMemTitle.fill = GridBagConstraints.HORIZONTAL;
		gbc_addMemTitle.insets = new Insets(0, 0, 5, 5);
		gbc_addMemTitle.gridx = 2;
		gbc_addMemTitle.gridy = 2;
		jPanel2.add(addMemTitle, gbc_addMemTitle);
		jLabel11 = new javax.swing.JLabel();
		jLabel11.setFont(new Font("Tahoma", Font.PLAIN, 18));

		jLabel11.setText("Membership type:");
		GridBagConstraints gbc_jLabel11 = new GridBagConstraints();
		gbc_jLabel11.anchor = GridBagConstraints.NORTHWEST;
		gbc_jLabel11.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel11.gridx = 4;
		gbc_jLabel11.gridy = 2;
		jPanel2.add(jLabel11, gbc_jLabel11);
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setFont(new Font("Tahoma", Font.PLAIN, 18));

		jLabel3.setText("First Name");
		GridBagConstraints gbc_jLabel3 = new GridBagConstraints();
		gbc_jLabel3.fill = GridBagConstraints.HORIZONTAL;
		gbc_jLabel3.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel3.gridx = 1;
		gbc_jLabel3.gridy = 3;
		jPanel2.add(jLabel3, gbc_jLabel3);
		addMemFiNa = new javax.swing.JTextField();
		GridBagConstraints gbc_addMemFiNa = new GridBagConstraints();
		gbc_addMemFiNa.fill = GridBagConstraints.HORIZONTAL;
		gbc_addMemFiNa.insets = new Insets(0, 0, 5, 5);
		gbc_addMemFiNa.gridx = 2;
		gbc_addMemFiNa.gridy = 3;
		jPanel2.add(addMemFiNa, gbc_addMemFiNa);
		jComboBox7 = new javax.swing.JComboBox<>();
		jComboBox7.setFont(new Font("Tahoma", Font.PLAIN, 18));

		jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(lDB.getMemberships()));
		jComboBox7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox7ActionPerformed(evt);
			}
		});
		GridBagConstraints gbc_jComboBox7 = new GridBagConstraints();
		gbc_jComboBox7.anchor = GridBagConstraints.WEST;
		gbc_jComboBox7.insets = new Insets(0, 0, 5, 5);
		gbc_jComboBox7.gridx = 4;
		gbc_jComboBox7.gridy = 3;
		jPanel2.add(jComboBox7, gbc_jComboBox7);
		jLabel4 = new javax.swing.JLabel();
		jLabel4.setFont(new Font("Tahoma", Font.PLAIN, 18));

		jLabel4.setText("Surname");
		GridBagConstraints gbc_jLabel4 = new GridBagConstraints();
		gbc_jLabel4.anchor = GridBagConstraints.WEST;
		gbc_jLabel4.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel4.gridx = 1;
		gbc_jLabel4.gridy = 4;
		jPanel2.add(jLabel4, gbc_jLabel4);
		addMemLaNa = new javax.swing.JTextField();
		GridBagConstraints gbc_addMemLaNa = new GridBagConstraints();
		gbc_addMemLaNa.fill = GridBagConstraints.HORIZONTAL;
		gbc_addMemLaNa.insets = new Insets(0, 0, 5, 5);
		gbc_addMemLaNa.gridx = 2;
		gbc_addMemLaNa.gridy = 4;
		jPanel2.add(addMemLaNa, gbc_addMemLaNa);
		jLabel5 = new javax.swing.JLabel();
		jLabel5.setFont(new Font("Tahoma", Font.PLAIN, 18));

		jLabel5.setText("Address");
		GridBagConstraints gbc_jLabel5 = new GridBagConstraints();
		gbc_jLabel5.anchor = GridBagConstraints.WEST;
		gbc_jLabel5.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel5.gridx = 1;
		gbc_jLabel5.gridy = 5;
		jPanel2.add(jLabel5, gbc_jLabel5);
		addMemAd = new javax.swing.JTextField();
		GridBagConstraints gbc_addMemAd = new GridBagConstraints();
		gbc_addMemAd.fill = GridBagConstraints.HORIZONTAL;
		gbc_addMemAd.insets = new Insets(0, 0, 5, 5);
		gbc_addMemAd.gridx = 2;
		gbc_addMemAd.gridy = 5;
		jPanel2.add(addMemAd, gbc_addMemAd);
		jLabel7 = new javax.swing.JLabel();
		jLabel7.setFont(new Font("Tahoma", Font.PLAIN, 18));

		jLabel7.setText("Phone #");
		GridBagConstraints gbc_jLabel7 = new GridBagConstraints();
		gbc_jLabel7.anchor = GridBagConstraints.WEST;
		gbc_jLabel7.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel7.gridx = 1;
		gbc_jLabel7.gridy = 6;
		jPanel2.add(jLabel7, gbc_jLabel7);
		addMemPhone = new javax.swing.JTextField();
		GridBagConstraints gbc_addMemPhone = new GridBagConstraints();
		gbc_addMemPhone.fill = GridBagConstraints.HORIZONTAL;
		gbc_addMemPhone.insets = new Insets(0, 0, 5, 5);
		gbc_addMemPhone.gridx = 2;
		gbc_addMemPhone.gridy = 6;
		jPanel2.add(addMemPhone, gbc_addMemPhone);
		jLabel8 = new javax.swing.JLabel();
		jLabel8.setFont(new Font("Tahoma", Font.PLAIN, 18));

		jLabel8.setText("D.O.B");
		GridBagConstraints gbc_jLabel8 = new GridBagConstraints();
		gbc_jLabel8.anchor = GridBagConstraints.WEST;
		gbc_jLabel8.insets = new Insets(0, 0, 5, 5);
		gbc_jLabel8.gridx = 1;
		gbc_jLabel8.gridy = 7;
		jPanel2.add(jLabel8, gbc_jLabel8);
		addMemDOB = new javax.swing.JTextField();
		GridBagConstraints gbc_addMemDOB = new GridBagConstraints();
		gbc_addMemDOB.fill = GridBagConstraints.HORIZONTAL;
		gbc_addMemDOB.insets = new Insets(0, 0, 5, 5);
		gbc_addMemDOB.gridx = 2;
		gbc_addMemDOB.gridy = 7;
		jPanel2.add(addMemDOB, gbc_addMemDOB);
		jButton2 = new javax.swing.JButton();
		jButton2.setFont(new Font("Tahoma", Font.PLAIN, 18));

		jButton2.setText("Create Member");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				
				
				StringBuilder fNameWTi = null;
				String titled,tm, fn, ln, ad, ph, dBirth;
				Double bal = 0.0;
				int memType;
				
				
				dBirth = addMemDOB.getText();	
				tm = addMemTitle.getText();
				fn = addMemFiNa.getText();
				
				fNameWTi.append(tm);
				fNameWTi.append(fn);
				
				titled = fNameWTi.toString();
				
				
				ln = addMemLaNa.getText();
				ad = addMemAd.getText();
				
				ph = addMemPhone.getText();
				
				memType = jComboBox7.
				
				lDB.addMember(typeMembership, titled, ln, dBirth, ad, ph, bal);
				
				
				
				
				jButton2ActionPerformed(evt);
			}
		});
		GridBagConstraints gbc_jButton2 = new GridBagConstraints();
		gbc_jButton2.fill = GridBagConstraints.HORIZONTAL;
		gbc_jButton2.insets = new Insets(0, 0, 5, 5);
		gbc_jButton2.gridx = 4;
		gbc_jButton2.gridy = 7;
		jPanel2.add(jButton2, gbc_jButton2);

		panel = new JPanel();
		jTabbedPane3.addTab("Edit Memeber", null, panel, null);
		GridBagLayout gbl_panel = new GridBagLayout();
		gbl_panel.columnWidths = new int[] {30, 30, 160, 30, 167, 81, 30, 82};
		gbl_panel.rowHeights = new int[]{27, 0, 26, 29, 29, 26, 26, 26, 26, 39, 0, 0};
		gbl_panel.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
		gbl_panel.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		panel.setLayout(gbl_panel);

		label = new JLabel();
		label.setText("Member To Update");
		label.setFont(new Font("Tahoma", Font.BOLD, 22));
		GridBagConstraints gbc_label = new GridBagConstraints();
		gbc_label.anchor = GridBagConstraints.NORTHWEST;
		gbc_label.insets = new Insets(0, 0, 5, 5);
		gbc_label.gridwidth = 3;
		gbc_label.gridx = 1;
		gbc_label.gridy = 1;
		panel.add(label, gbc_label);

		button = new JButton();
		button.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			}
		});

		label_9 = new JLabel();
		label_9.setText("Member ID");
		label_9.setFont(new Font("Tahoma", Font.BOLD, 22));
		GridBagConstraints gbc_label_9 = new GridBagConstraints();
		gbc_label_9.anchor = GridBagConstraints.NORTHWEST;
		gbc_label_9.insets = new Insets(0, 0, 5, 0);
		gbc_label_9.gridwidth = 4;
		gbc_label_9.gridx = 4;
		gbc_label_9.gridy = 1;
		panel.add(label_9, gbc_label_9);

		label_6 = new JLabel();
		label_6.setFont(new Font("Tahoma", Font.PLAIN, 18));
		label_6.setText("Title");
		GridBagConstraints gbc_label_6 = new GridBagConstraints();
		gbc_label_6.anchor = GridBagConstraints.NORTH;
		gbc_label_6.fill = GridBagConstraints.HORIZONTAL;
		gbc_label_6.insets = new Insets(0, 0, 5, 5);
		gbc_label_6.gridx = 1;
		gbc_label_6.gridy = 4;
		panel.add(label_6, gbc_label_6);

		textField_1 = new JTextField();
		textField_1.setText("jTextField2");
		GridBagConstraints gbc_textField_1 = new GridBagConstraints();
		gbc_textField_1.anchor = GridBagConstraints.NORTH;
		gbc_textField_1.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_1.insets = new Insets(0, 0, 5, 5);
		gbc_textField_1.gridx = 2;
		gbc_textField_1.gridy = 4;
		panel.add(textField_1, gbc_textField_1);

		label_3 = new JLabel();
		label_3.setFont(new Font("Tahoma", Font.PLAIN, 18));
		label_3.setText("Mem Id");
		GridBagConstraints gbc_label_3 = new GridBagConstraints();
		gbc_label_3.anchor = GridBagConstraints.NORTHWEST;
		gbc_label_3.insets = new Insets(0, 0, 5, 5);
		gbc_label_3.gridx = 4;
		gbc_label_3.gridy = 4;
		panel.add(label_3, gbc_label_3);

		textField = new JTextField();
		textField.setText("jTextField1");
		GridBagConstraints gbc_textField = new GridBagConstraints();
		gbc_textField.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField.anchor = GridBagConstraints.NORTH;
		gbc_textField.insets = new Insets(0, 0, 5, 0);
		gbc_textField.gridwidth = 3;
		gbc_textField.gridx = 5;
		gbc_textField.gridy = 4;
		panel.add(textField, gbc_textField);

		label_7 = new JLabel();
		label_7.setFont(new Font("Tahoma", Font.PLAIN, 18));
		label_7.setText("First Name");
		GridBagConstraints gbc_label_7 = new GridBagConstraints();
		gbc_label_7.anchor = GridBagConstraints.WEST;
		gbc_label_7.insets = new Insets(0, 0, 5, 5);
		gbc_label_7.gridx = 1;
		gbc_label_7.gridy = 5;
		panel.add(label_7, gbc_label_7);

		textField_2 = new JTextField();
		textField_2.setText("jTextField3");
		GridBagConstraints gbc_textField_2 = new GridBagConstraints();
		gbc_textField_2.anchor = GridBagConstraints.NORTH;
		gbc_textField_2.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_2.insets = new Insets(0, 0, 5, 5);
		gbc_textField_2.gridx = 2;
		gbc_textField_2.gridy = 5;
		panel.add(textField_2, gbc_textField_2);

		JButton button_1 = new JButton();
		button_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
			}
		});
		button_1.setText("Confirm Member");
		GridBagConstraints gbc_button_1 = new GridBagConstraints();
		gbc_button_1.anchor = GridBagConstraints.NORTHWEST;
		gbc_button_1.insets = new Insets(0, 0, 5, 5);
		gbc_button_1.gridx = 4;
		gbc_button_1.gridy = 5;
		panel.add(button_1, gbc_button_1);

		label_8 = new JLabel();
		label_8.setFont(new Font("Tahoma", Font.PLAIN, 18));
		label_8.setText("Surname");
		GridBagConstraints gbc_label_8 = new GridBagConstraints();
		gbc_label_8.anchor = GridBagConstraints.NORTHWEST;
		gbc_label_8.insets = new Insets(0, 0, 5, 5);
		gbc_label_8.gridx = 1;
		gbc_label_8.gridy = 6;
		panel.add(label_8, gbc_label_8);

		textField_3 = new JTextField();
		textField_3.setText("jTextField4");
		GridBagConstraints gbc_textField_3 = new GridBagConstraints();
		gbc_textField_3.anchor = GridBagConstraints.SOUTH;
		gbc_textField_3.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_3.insets = new Insets(0, 0, 5, 5);
		gbc_textField_3.gridx = 2;
		gbc_textField_3.gridy = 6;
		panel.add(textField_3, gbc_textField_3);

		label_4 = new JLabel();
		label_4.setFont(new Font("Tahoma", Font.PLAIN, 18));
		label_4.setText("Address");
		GridBagConstraints gbc_label_4 = new GridBagConstraints();
		gbc_label_4.anchor = GridBagConstraints.NORTHWEST;
		gbc_label_4.insets = new Insets(0, 0, 5, 5);
		gbc_label_4.gridx = 1;
		gbc_label_4.gridy = 7;
		panel.add(label_4, gbc_label_4);

		textField_4 = new JTextField();
		textField_4.setText("jTextField5");
		GridBagConstraints gbc_textField_4 = new GridBagConstraints();
		gbc_textField_4.anchor = GridBagConstraints.NORTH;
		gbc_textField_4.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_4.insets = new Insets(0, 0, 5, 5);
		gbc_textField_4.gridx = 2;
		gbc_textField_4.gridy = 7;
		panel.add(textField_4, gbc_textField_4);

		lblPhone = new JLabel();
		lblPhone.setFont(new Font("Tahoma", Font.PLAIN, 18));
		lblPhone.setText("Phone #");
		GridBagConstraints gbc_lblPhone = new GridBagConstraints();
		gbc_lblPhone.anchor = GridBagConstraints.NORTHWEST;
		gbc_lblPhone.insets = new Insets(0, 0, 5, 5);
		gbc_lblPhone.gridx = 1;
		gbc_lblPhone.gridy = 8;
		panel.add(lblPhone, gbc_lblPhone);

		textField_5 = new JTextField();
		textField_5.setText("jTextField6");
		GridBagConstraints gbc_textField_5 = new GridBagConstraints();
		gbc_textField_5.anchor = GridBagConstraints.NORTH;
		gbc_textField_5.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_5.insets = new Insets(0, 0, 5, 5);
		gbc_textField_5.gridx = 2;
		gbc_textField_5.gridy = 8;
		panel.add(textField_5, gbc_textField_5);

		label_2 = new JLabel();
		label_2.setFont(new Font("Tahoma", Font.PLAIN, 18));
		label_2.setText("D.O.B");
		GridBagConstraints gbc_label_2 = new GridBagConstraints();
		gbc_label_2.anchor = GridBagConstraints.NORTHWEST;
		gbc_label_2.insets = new Insets(0, 0, 5, 5);
		gbc_label_2.gridx = 1;
		gbc_label_2.gridy = 9;
		panel.add(label_2, gbc_label_2);

		textField_6 = new JTextField();
		textField_6.setText("jTextField7");
		GridBagConstraints gbc_textField_6 = new GridBagConstraints();
		gbc_textField_6.anchor = GridBagConstraints.NORTH;
		gbc_textField_6.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_6.insets = new Insets(0, 0, 5, 5);
		gbc_textField_6.gridx = 2;
		gbc_textField_6.gridy = 9;
		panel.add(textField_6, gbc_textField_6);
		button.setText("Update Member");
		GridBagConstraints gbc_button = new GridBagConstraints();
		gbc_button.anchor = GridBagConstraints.WEST;
		gbc_button.fill = GridBagConstraints.VERTICAL;
		gbc_button.insets = new Insets(0, 0, 0, 5);
		gbc_button.gridx = 1;
		gbc_button.gridy = 10;
		panel.add(button, gbc_button);

		panel_1 = new JPanel();
		jTabbedPane3.addTab("Delete Member", null, panel_1, null);
		GridBagLayout gbl_panel_1 = new GridBagLayout();
		gbl_panel_1.columnWidths = new int[]{30, 30, 160, 30, 167, 81, 30, 82, 0};
		gbl_panel_1.rowHeights = new int[]{27, 0, 26, 29, 29, 26, 26, 26, 26, 39, 0};
		gbl_panel_1.columnWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		gbl_panel_1.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, Double.MIN_VALUE};
		panel_1.setLayout(gbl_panel_1);

		lblMemberToDelete = new JLabel();
		lblMemberToDelete.setText("Member To Delete");
		lblMemberToDelete.setFont(new Font("Tahoma", Font.BOLD, 22));
		GridBagConstraints gbc_lblMemberToDelete = new GridBagConstraints();
		gbc_lblMemberToDelete.anchor = GridBagConstraints.NORTHWEST;
		gbc_lblMemberToDelete.gridwidth = 3;
		gbc_lblMemberToDelete.insets = new Insets(0, 0, 5, 5);
		gbc_lblMemberToDelete.gridx = 1;
		gbc_lblMemberToDelete.gridy = 1;
		panel_1.add(lblMemberToDelete, gbc_lblMemberToDelete);

		lblMemberId = new JLabel();
		lblMemberId.setText("Member ID");
		lblMemberId.setFont(new Font("Tahoma", Font.PLAIN, 18));
		GridBagConstraints gbc_lblMemberId = new GridBagConstraints();
		gbc_lblMemberId.fill = GridBagConstraints.HORIZONTAL;
		gbc_lblMemberId.anchor = GridBagConstraints.NORTH;
		gbc_lblMemberId.insets = new Insets(0, 0, 5, 5);
		gbc_lblMemberId.gridx = 1;
		gbc_lblMemberId.gridy = 3;
		panel_1.add(lblMemberId, gbc_lblMemberId);

		textField_8 = new JTextField();
		textField_8.setText("jTextField2");
		GridBagConstraints gbc_textField_8 = new GridBagConstraints();
		gbc_textField_8.fill = GridBagConstraints.HORIZONTAL;
		gbc_textField_8.anchor = GridBagConstraints.NORTH;
		gbc_textField_8.insets = new Insets(0, 0, 5, 5);
		gbc_textField_8.gridx = 2;
		gbc_textField_8.gridy = 3;
		panel_1.add(textField_8, gbc_textField_8);

		btnDeleteMember = new JButton();
		btnDeleteMember.setText("Delete Member");
		GridBagConstraints gbc_btnDeleteMember = new GridBagConstraints();
		gbc_btnDeleteMember.fill = GridBagConstraints.VERTICAL;
		gbc_btnDeleteMember.anchor = GridBagConstraints.WEST;
		gbc_btnDeleteMember.insets = new Insets(0, 0, 5, 5);
		gbc_btnDeleteMember.gridx = 2;
		gbc_btnDeleteMember.gridy = 4;
		panel_1.add(btnDeleteMember, gbc_btnDeleteMember);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(LeisureCentre)
						.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(LeisureCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 19, Short.MAX_VALUE))
				);

		tabbedPane = new JTabbedPane();
		LeisureCentre.addTab("Staff", null, tabbedPane, null);

		tabbedPane_1 = new JTabbedPane();
		tabbedPane.addTab("New tab", null, tabbedPane_1, null);

		tabbedPane_2 = new JTabbedPane();
		tabbedPane.addTab("New tab", null, tabbedPane_2, null);

		LeisureCentre.getAccessibleContext().setAccessibleName("Booking");

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jButton2ActionPerformed

	private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jComboBox7ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(leisureCentreProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				leisureCentreProject p;
				try {
					p = new leisureCentreProject();
					p.setVisible(true);
					p.pack();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}

				//p.setResizable(false);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTabbedPane LeisureCentre;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JComboBox<String> jComboBox7;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTabbedPane jTabbedPane3;
	private javax.swing.JTabbedPane jTabbedPane6;
	private javax.swing.JTextField addMemTitle;
	private javax.swing.JTextField addMemFiNa;
	private javax.swing.JTextField addMemLaNa;
	private javax.swing.JTextField addMemAd;
	private javax.swing.JTextField addMemPhone;
	private javax.swing.JTextField addMemDOB;
	private JPanel panel;
	private JLabel label;
	private JLabel lblPhone;
	private JLabel label_2;
	private JLabel label_3;
	private JLabel label_4;
	private JLabel label_6;
	private JLabel label_7;
	private JLabel label_8;
	private JTextField textField;
	private JTextField textField_1;
	private JTextField textField_2;
	private JTextField textField_3;
	private JTextField textField_4;
	private JTextField textField_5;
	private JTextField textField_6;
	private JLabel label_9;
	private JButton button;
	private JLabel lblNewLabel;
	private JTable table;
	private JTable table_1;
	private JPanel panel_1;
	private JLabel lblMemberToDelete;
	private JLabel lblMemberId;
	private JTextField textField_8;
	private JButton btnDeleteMember;
	private JTabbedPane tabbedPane;
	private JTabbedPane tabbedPane_1;
	private JTabbedPane tabbedPane_2;
	private JTable table_2;
}
